name: test
on: push
jobs:
  build:
    runs-on:  ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v6
      - name: seleep 5 seconds
        run: sleep 5
      - name: run multi line command
        run: |
          echo add other action to build,
          echo test and deploy your project
